### ISSUE TITLE
bet put/call AUDJPY by api

### ISSUE THREAD

**Issue by paramon161616** [binary-com/binary-live-api#129]
how can i bet put/call using api? 

In web socket traffic I found this, can I use it? 

Where to get purchase-id?

- {
  "buy": "12-34-12-34",
  "price": "10",
  "passthrough": {
    "display_value": "10",
    "payout": "18.69",
    "purchase-id": "12-34-12-34",
    "ask-price": "10",
    "symbol": "frxAUDJPY",
    "amount": "10",
    "basis": "stake",
    "contract_type": "PUT",
    "currency": "USD",
    "duration": "5",
    "duration_unit": "t",
    "product_type": "basic",
    "req_id": "33",
    "subscribe": "1"
  },
  "req_id": 36
}

in official API https://developers.binary.com/api/#buy I find just  strange *Buy a Contract Send*

![image](https://user-images.githubusercontent.com/16824372/58333504-3d229d80-7e46-11e9-81c5-1a1a270d8987.png)

**Comment by wilburforce83** [comment]
https://github.com/binary-com/binary-live-api/issues/114

**Comment by wilburforce83** [comment]
to get the I'd `let buyid = response.buy` should get you it

**Comment by paramon161616** [comment]
> #114

no solution there

**Comment by wilburforce83** [comment]
#114 *is* the solution. i.e. buy without a proposal. Buy without a proposal then use the contract_id to keep track of the trade until it closes. The API is a bit of a jumble as far as I could tell, I've built a trading platform for it and I have had to write workarounds for nearly every part of it.

What is it exactly that you are after? I can try and help :)

**Comment by wilburforce83** [comment]
This is how I am placing a trade:

```
 const parameters = {
            amount: settings.get('stake.stake'), // '0.35'
            basis: 'stake', // or 'payout'
            contract_type: settings.get('callOrPut.callOrPut'), // or 'CALL / PUT'
            currency: settings.get('currency.currency'),
            duration: duration, // '5'
            duration_unit: duration_unit, //'t'/ 's'/ 'm' etc
            symbol: signal, // symbol 'R_100' or frxAUDJPY
        };

       api.authorize(token).then(function resolve(resp) {



                api.buyContractParams(parameters, 2500).then(

                    (response, reject) => {
                        console.log(response);
                        let time = moment().format("kk:mm:ss");
                        let contract_id = response.buy.contract_id;
                        let longCode = response.buy.longcode;
                        let newBalance = response.buy.balance_after;


blah, blah

}).catch // blah blah
```

**Comment by paramon161616** [comment]
> #114 _is_ the solution. i.e. buy without a proposal. Buy without a proposal then use the contract_id to keep track of the trade until it closes. The API is a bit of a jumble as far as I could tell, I've built a trading platform for it and I have had to write workarounds for nearly every part of it.
> 
> What is it exactly that you are after? I can try and help :)

I want to press purchase  button by api and set Durstion ans Stake values

I wrote bot - eur/usd predictor and want to connect it to  the binary com. by official api I can only get 1 sec. frame price. and I want to bet 

![image](https://user-images.githubusercontent.com/16824372/58345064-1ffac880-7e60-11e9-8c48-725c8cc25084.png)

**Comment by paramon161616** [comment]
> This is how I am placing a trade:
> 
> ```
>  const parameters = {
>             amount: settings.get('stake.stake'), // '0.35'
>             basis: 'stake', // or 'payout'
>             contract_type: settings.get('callOrPut.callOrPut'), // or 'CALL / PUT'
>             currency: settings.get('currency.currency'),
>             duration: duration, // '5'
>             duration_unit: duration_unit, //'t'/ 's'/ 'm' etc
>             symbol: signal, // symbol 'R_100' or frxAUDJPY
>         };
> 
>        api.authorize(token).then(function resolve(resp) {
> 
> 
> 
>                 api.buyContractParams(parameters, 2500).then(
> 
>                     (response, reject) => {
>                         console.log(response);
>                         let time = moment().format("kk:mm:ss");
>                         let contract_id = response.buy.contract_id;
>                         let longCode = response.buy.longcode;
>                         let newBalance = response.buy.balance_after;
> 
> 
> blah, blah
> 
> }).catch // blah blah
> ```

thanks. can you write json structure for this request? Im c# developer :-))

**Comment by wilburforce83** [comment]
I'm not really sure I understand. It sounds like you'd be better off just using something like Kantu to manipulate the DOM and press buttons etc on a macro. If you want to use the official site? Am I missing something?

**Comment by paramon161616** [comment]
> I'm not really sure I understand. It sounds like you'd be better off just using something like Kantu to manipulate the DOM and press buttons etc on a macro. If you want to use the official site? Am I missing something?

i find the function on the site. and i search api endpoints for same purpose (bet on higher  / lower price)

**Comment by wilburforce83** [comment]
I still don't get it, are you trying to place trades through the site, via console? i.e. bypass the UI?I'm not sure that will work to be honest.

The site, I think, buys off proposals, which means you need a proposal in order to place the trade. I haven't done this, so I'm not 100%. but I think the string you need is this one:

![image](https://user-images.githubusercontent.com/17556774/58348654-20439580-7e59-11e9-8640-c0522b86d914.png)

you need to pass the parameters of your desired trade :
```
const parameters = {
  "proposal": 1,
  "amount": "100",
  "basis": "stake",
  "contract_type": "CALL",
  "currency": "USD",
  "duration": "30",
  "duration_unit": "s",
  "barrier": "+0.1",
  "symbol": "R_100"
}
```

I think the function is:

`api.getPriceProposalForContract(parameters)`

you'll then need to pull the info out:

```
.then(

                    (response, reject) => {
//map what you need hereprobably:
let proposal_id =response.proposal.id
}).catch
```

But I never really looked into it any further as I found buying without a proposal a much better solution. It is probably worth looking through the source code of the webtrader (probably similar to smart trader) to see exactly what they are doing, ormaybe this will help?

https://github.com/binary-com/Binary-WS-endpoint-extension

**Comment by paramon161616** [comment]
Thanks. it works

**Comment by wilburforce83** [comment]
Excellent!
