### ISSUE TITLE
Api Get Trading Durations

### ISSUE THREAD

**Issue by victorfds** [binary-com/binary-live-api#144]
Is there a way to get trading durations like described in https://developers.binary.com/api/#trading_durations ?

**Comment by wilburforce83** [comment]
@victorfds  You can get it all from here, then filter `response` :
``` 
api.getAssetIndex().then(function (response) {

console.log(response)

// blah do stuff here

});
```

**Comment by victorfds** [comment]
> @victorfds You can get it all from here, then filter `response` :
> 
> ```
> api.getAssetIndex().then(function (response) {
> 
> console.log(response)
> 
> // blah do stuff here
> 
> });
> ```

Thank you.
