### ISSUE TITLE
Buy Contract for BTC Account 

### ISSUE THREAD

**Issue by keepdoolabs** [binary-com/binary-live-api#150]
when I try to buy a contract on the BTC account, it returns this error: 

Invalid amount. Amount provided can not have more than 2 decimal places. 

I need help.

**Comment by wilburforce83** [comment]
I don't use BTC but what are is the contract price you are tyring to buy when you receive this error?

console.log your contract price variable, make sure it's not more than 2 dp? then why not make sure it's always correct to 2 DP with:

`Math.floor(contract * 100)/100` ?

**Comment by keepdoolabs** [comment]
> I don't use BTC but what are is the contract price you are tyring to buy when you receive this error?
> 
> console.log your contract price variable, make sure it's not more than 2 dp? then why not make sure it's always correct to 2 DP with:
> 
> `Math.floor(contract * 100)/100` ?
