### ISSUE TITLE
documentation misleading

### ISSUE THREAD

**Issue by lwhiteley** [binary-com/binary-live-api#50]
i followed the documentation for using this in nodejs but was getting no response.

took me some time investigating the code to realise a couple things 
1. the constructor accepts an object where the `ws` library should be passed as the `websocket` property
2. calls that require auth have to wait on confirmation before you can execute

so my code looks something like below

```js
var ws = require('ws');
var LiveApi = require('binary-live-api').LiveApi;
var api = new LiveApi({websocket:ws});

api.authorize('XXXXXXXXXXXX').then(function(){

  api.getProfitTable()
  .then(function(results){
    console.log(results)
  });

});
```

while your documentation has

```js
var ws = require('ws');
var LiveApi = require('binary-live-api').LiveApi;

var api = new LiveApi(ws);
api.authorize('yourtoken');
api.getPortfolio();
api.events.on('portfolio', function(data) {
    // do stuff with portfolio data
});
```

**Comment by borisyankov** [comment]
Oh, yes, you are correct in #1. We did change the parameters, now it gets an object. Will fix the documentation.

Your code is good.
But the example code is also correct.
There are two ways to use the API, with and without Promises.
And in that usage api.authorize and api.getPortfolio are asynchronous, you can immediately call getPortfolio and it will not be sent before authorize is processed.

Using Promises as you do though is preferred.

**Comment by lwhiteley** [comment]
semantically it is correct, but if you want it to actually be useful its not..

when i follow the docs, this is the result

```js
{ echo_req: { portfolio: 1, req_id: 133416957221925 },
  req_id: 133416957221925,
  error: { message: 'Please log in.', code: 'AuthorizationRequired' },
  msg_type: 'portfolio' }
```

so if i wanted to use events i would still need to wait and do something like the following
```js

api.events.on('authorize', function(results){
   api.getPortfolio();
})

api.events.on('portfolio', function(data) {
    console.log(data)
});
```

this now gets the portfolio data

**Comment by borisyankov** [comment]
Hmmm, I 'll need to test this, but it behaves unexpectedly.
The responses sure are async, but the requests sent are queued on a single connection and executed one by one on the server.

**Comment by lwhiteley** [comment]
are you saying that each request waits for a response before moving on ?

unless you use a handler like q to delay the process then it will not wait on the response but return a promise and execute the next call. All responses will be return asynchronously hence it turns into a race

**Comment by borisyankov** [comment]
The function call itself asynchronous.
On the other hand, since everything happens over a single socket, calls are sent sequentially, and responses received sequentially, though the execution of the calls on the server is possibly parallelized.

In the end, I agree, Promises are certainly better and less error-prone.
