### ISSUE TITLE
Any plans to allow date formatted values for getStatment date/time parameters?

### ISSUE THREAD

**Issue by lwhiteley** [binary-com/binary-live-api#68]
Currently the Get Profit Table method can allow you to use a date formatted (YYYY-MM-DD) value for date_from and date_to.

Is there a reason why this isn't consistent for the Get Statement method?
Any plans on adding this feature for the Get Statement Method?

**Just to note:** Not a blocker but consistency would be nice

Regards

See screenshots below

Profit Table Docs
![Get Statement Docs](https://i.imgur.com/S0KHlg8.png)

VS 

Get Statement Docs 
![Get Statement Docs](https://i.imgur.com/oF8bqb9.png)

**Comment by borisyankov** [comment]
There are definitely plans to unify all date formats. It is a breaking change though.
We will implement this when we move to version 4 of the API (hopefully soon).
