### ISSUE TITLE
How to catch an error?

### ISSUE THREAD

**Issue by raitucarp** [binary-com/binary-live-api#7]
Could you provide onerror listener such as events.on("error", function(message)) ?

And where is the documentation of error messages and its code?

**Comment by qingweibinary** [comment]
AFAIK, there's not documentation of error at the moment

**Comment by borisyankov** [comment]
We will add a per call handler as 

    on('specific_call',successHandler, errorHandler)


and we'll add a global error handler just as you suggested:

    on('error', errorHandler)
