### ISSUE TITLE
There's no unsubscribe call for candles

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-live-api#83]
Currently if I want to unsubscribe from candles I need to use send directly. But send is going to be deprecated.

**Comment by qingweibinary** [comment]
@aminmarashi how about unsubscribeById?

in fact unsubscribe from ticks does not work too, you have to use unsubscribeById

**Comment by aminmarashi** [comment]
I thought it's good to keep the forget_all calls working. In that case I have to refactor all my code to use the ids for unsubscription.

**Comment by qingweibinary** [comment]
@aminmarashi oh, so you're saying about forget_all, sorry I thought you were talking about unsubscribe single stream.

In that case, yea, it's a feature that we would add if backend support out of the box

**Comment by qingweibinary** [comment]
https://github.com/binary-com/binary-live-api/pull/86/commits/e6a36a03255f61d587a44577e9955ad9ca64d0fe

here you go

**Comment by borisyankov** [comment]
Published

**Comment by aminmarashi** [comment]
This is solved, thanks 👍
