### ISSUE TITLE
reconnecting does not subscribe to both ticks and candles

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-live-api#84]
If the user is subscribed to both ticks and candles (which is always the case in binary bot), after a reconnect only candle stream is recovered.

**Comment by qingweibinary** [comment]
I am working on this

**Comment by qingweibinary** [comment]
https://github.com/binary-com/binary-live-api/pull/86/commits/530740989dd59025f4a04eede5e84b173c6147b5

this should fix this

**Comment by aminmarashi** [comment]
Still for calls like buy which are critical the api doesn't return any kind of error in case of disconnect, it just fails silently. Obviously it shouldn't try again either.

**Comment by qingweibinary** [comment]
That's another issue, what do you expect when that happens, and is there any other calls other than buy that should be treated the same?

**Comment by aminmarashi** [comment]
Yeah, actually it's a global issue, I expect all calls to fail in case of connection loss unless they're subscriptions (which are automatically subscribed again). 
I opened this https://github.com/binary-com/binary-live-api/issues/87
