### ISSUE TITLE
Non-subscribing calls won't fail in case of connection loss

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-live-api#87]
Imagine you're buying a contract, a buy request is sent, right before getting the response your connection is lost, you should somehow become aware that this to investigate if you have to buy again or not.

**Comment by qingweibinary** [comment]
@aminmarashi I agree, let's discuss and come out with some general solution?

**Comment by qingweibinary** [comment]
Problem: 
for synchronous api, if websocket disconnect right after request, and right before response is received, how should it behaves?

This is pretty complicated, ideally, we should implement some transactional protocol for example 2Phase commit

But since Binary-bot is the only project that likely to face such problem alot, me and Amin agreed that live-api's behaviour would be

> When user issue a buy call, and websocket disconnected after request is sent, but before response is received, api will reject the promise with an exception `DisconnectedAfterBuyCall`


For other synchrounous call, we will wont do anything.

**Comment by qingweibinary** [comment]
Food for thought

http://programmers.stackexchange.com/questions/213135/what-to-do-when-request-is-sent-to-server-and-while-waiting-for-response-interne

**Comment by qingweibinary** [comment]
PR: https://github.com/binary-com/binary-live-api/pull/89

I did it a little bit different with what we've discussed, ie. it will reject all unresolved promise when disconnected. 

Reason

1. It's simpler to treat everything the same
2. It does not add complexity, and provide more flexibility, in case user want to also know why my active-symbols call never return.

**Comment by qingweibinary** [comment]
@aminmarashi does it works? if not please state how you test it, I'll investigate

Here is how I test though

https://github.com/qingweibinary/binary-live-api/blob/3115ce23b5bf9b9a5989703362e8df5138e43ae3/src/__tests__/resubscribe-test.js#L49

**Comment by aminmarashi** [comment]
I'll test and let you know, sorry for the delay.

**Comment by aminmarashi** [comment]
Works excellent, thank you very much 👍

**Comment by aminmarashi** [comment]
This PR https://github.com/binary-com/binary-live-api/pull/91 will fix it completely.

**Comment by aminmarashi** [comment]
Fixed
